apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3002
      nodePort: 31110